### ISSUE TITLE
Issue connecting to an external server.

### ISSUE THREAD

**Issue by narangrishab** [numtel/meteor-mysql-server#4]
<img width="1280" alt="screen shot 2015-09-03 at 3 53 37 pm" src="https://cloud.githubusercontent.com/assets/9140727/9656174/0985e27e-5254-11e5-8db3-b630c1dcc947.png">
Hello @numtel ,

I made a console.mysql.json file in my root directory. The server is hosted on AWS and I'm running my meteor app on localhost.

{
"host" : " ..... ",
"username" : "root",
"password" : "...",
"database": "...",
}

Also tried,
{
  "port": 3306,
  "initialize": "leaderboard.sql"
}

  var liveDb = new LiveMysql({
    host: '... ',
    // Port 3407 as specified in leaderboard.mysql.json
    // If using external MySQL server, the default port is 3306
    user: 'root',
    password: ' .. ',
    database: 'meteor'
  });

<img width="334" alt="screen shot 2015-09-03 at 3 41 36 pm" src="https://cloud.githubusercontent.com/assets/9140727/9655927/4fa1a308-5252-11e5-8714-3f8f6e100dee.png">

<img width="1280" alt="screen shot 2015-09-03 at 3 53 37 pm" src="https://cloud.githubusercontent.com/assets/9140727/9656593/03033fd4-5257-11e5-9465-4451efb8148e.png">

This doesn't seem to work. How can I add this?

**Comment by griiettner** [comment]
I'm having similar issue and it seems this issue was closed with no apparent solution...

Every time I try to initialize the leaderboard example... it fails

```
[[[[[ ~/Projects/Personal/meteor-mysql-leaderboard ]]]]]

=> Started proxy.                             
=> A patch (Meteor 1.2.0.2) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.                           
=> Started MySQL.                             
W20160816-14:17:52.497(-4)? (STDERR)          
W20160816-14:17:52.498(-4)? (STDERR) /Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:82
W20160816-14:17:52.499(-4)? (STDERR)         throw err;
W20160816-14:17:52.499(-4)? (STDERR)               ^
W20160816-14:17:52.499(-4)? (STDERR) Error: ER_NO_BINARY_LOGGING: You are not using binary logging
W20160816-14:17:52.499(-4)? (STDERR)     at Query.Sequence._packetToError (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
W20160816-14:17:52.499(-4)? (STDERR)     at Query.ErrorPacket (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
W20160816-14:17:52.499(-4)? (STDERR)     at Protocol._parsePacket (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
W20160816-14:17:52.499(-4)? (STDERR)     at Parser.write (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
W20160816-14:17:52.499(-4)? (STDERR)     at Protocol.write (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
W20160816-14:17:52.499(-4)? (STDERR)     at Socket.<anonymous> (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/Connection.js:82:28)
W20160816-14:17:52.500(-4)? (STDERR)     at Socket.emit (events.js:95:17)
W20160816-14:17:52.500(-4)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20160816-14:17:52.500(-4)? (STDERR)     at Socket.emit (events.js:92:17)
W20160816-14:17:52.500(-4)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20160816-14:17:52.500(-4)? (STDERR)     --------------------
W20160816-14:17:52.500(-4)? (STDERR)     at Protocol._enqueue (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:135:48)
W20160816-14:17:52.500(-4)? (STDERR)     at Connection.query (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/Connection.js:185:25)
W20160816-14:17:52.501(-4)? (STDERR)     at ZongJi._findBinlogEnd (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:126:23)
W20160816-14:17:52.501(-4)? (STDERR)     at nextMethod (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:67:22)
W20160816-14:17:52.501(-4)? (STDERR)     at /Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:71:9
W20160816-14:17:52.501(-4)? (STDERR)     at Query._callback (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:100:16)
W20160816-14:17:52.501(-4)? (STDERR)     at Query.Sequence.end (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
W20160816-14:17:52.501(-4)? (STDERR)     at Query.ErrorPacket (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
W20160816-14:17:52.501(-4)? (STDERR)     at Protocol._parsePacket (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
W20160816-14:17:52.502(-4)? (STDERR)     at Parser.write (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
=> Exited with code: 8
W20160816-14:17:59.665(-4)? (STDERR)          
W20160816-14:17:59.666(-4)? (STDERR) /Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:82
W20160816-14:17:59.666(-4)? (STDERR)         throw err;
W20160816-14:17:59.667(-4)? (STDERR)               ^
W20160816-14:17:59.667(-4)? (STDERR) Error: ER_NO_BINARY_LOGGING: You are not using binary logging
W20160816-14:17:59.667(-4)? (STDERR)     at Query.Sequence._packetToError (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
W20160816-14:17:59.667(-4)? (STDERR)     at Query.ErrorPacket (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
W20160816-14:17:59.667(-4)? (STDERR)     at Protocol._parsePacket (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
W20160816-14:17:59.667(-4)? (STDERR)     at Parser.write (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
W20160816-14:17:59.667(-4)? (STDERR)     at Protocol.write (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
W20160816-14:17:59.667(-4)? (STDERR)     at Socket.<anonymous> (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/Connection.js:82:28)
W20160816-14:17:59.667(-4)? (STDERR)     at Socket.emit (events.js:95:17)
W20160816-14:17:59.667(-4)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20160816-14:17:59.667(-4)? (STDERR)     at Socket.emit (events.js:92:17)
W20160816-14:17:59.667(-4)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20160816-14:17:59.668(-4)? (STDERR)     --------------------
W20160816-14:17:59.668(-4)? (STDERR)     at Protocol._enqueue (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:135:48)
W20160816-14:17:59.668(-4)? (STDERR)     at Connection.query (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/Connection.js:185:25)
W20160816-14:17:59.668(-4)? (STDERR)     at ZongJi._findBinlogEnd (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:126:23)
W20160816-14:17:59.668(-4)? (STDERR)     at nextMethod (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:67:22)
W20160816-14:17:59.668(-4)? (STDERR)     at /Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:71:9
W20160816-14:17:59.668(-4)? (STDERR)     at Query._callback (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:100:16)
W20160816-14:17:59.668(-4)? (STDERR)     at Query.Sequence.end (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
W20160816-14:17:59.668(-4)? (STDERR)     at Query.ErrorPacket (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
W20160816-14:17:59.668(-4)? (STDERR)     at Protocol._parsePacket (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
W20160816-14:17:59.668(-4)? (STDERR)     at Parser.write (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
=> Exited with code: 8
W20160816-14:18:06.882(-4)? (STDERR)          
W20160816-14:18:06.883(-4)? (STDERR) /Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:82
W20160816-14:18:06.883(-4)? (STDERR)         throw err;
W20160816-14:18:06.883(-4)? (STDERR)               ^
W20160816-14:18:06.883(-4)? (STDERR) Error: ER_NO_BINARY_LOGGING: You are not using binary logging
W20160816-14:18:06.884(-4)? (STDERR)     at Query.Sequence._packetToError (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
W20160816-14:18:06.884(-4)? (STDERR)     at Query.ErrorPacket (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
W20160816-14:18:06.884(-4)? (STDERR)     at Protocol._parsePacket (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
W20160816-14:18:06.884(-4)? (STDERR)     at Parser.write (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
W20160816-14:18:06.884(-4)? (STDERR)     at Protocol.write (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:39:16)
W20160816-14:18:06.884(-4)? (STDERR)     at Socket.<anonymous> (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/Connection.js:82:28)
W20160816-14:18:06.884(-4)? (STDERR)     at Socket.emit (events.js:95:17)
W20160816-14:18:06.884(-4)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20160816-14:18:06.884(-4)? (STDERR)     at Socket.emit (events.js:92:17)
W20160816-14:18:06.884(-4)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
W20160816-14:18:06.885(-4)? (STDERR)     --------------------
W20160816-14:18:06.885(-4)? (STDERR)     at Protocol._enqueue (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:135:48)
W20160816-14:18:06.885(-4)? (STDERR)     at Connection.query (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/Connection.js:185:25)
W20160816-14:18:06.885(-4)? (STDERR)     at ZongJi._findBinlogEnd (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:126:23)
W20160816-14:18:06.885(-4)? (STDERR)     at nextMethod (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:67:22)
W20160816-14:18:06.885(-4)? (STDERR)     at /Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:71:9
W20160816-14:18:06.885(-4)? (STDERR)     at Query._callback (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/index.js:100:16)
W20160816-14:18:06.885(-4)? (STDERR)     at Query.Sequence.end (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
W20160816-14:18:06.885(-4)? (STDERR)     at Query.ErrorPacket (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
W20160816-14:18:06.885(-4)? (STDERR)     at Protocol._parsePacket (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Protocol.js:271:23)
W20160816-14:18:06.885(-4)? (STDERR)     at Parser.write (/Users/griiettner/.meteor/packages/numtel_mysql/.1.0.3.1swivtj++os+web.browser+web.cordova/npm/node_modules/mysql-live-select/node_modules/zongji/node_modules/mysql/lib/protocol/Parser.js:77:12)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

The Connection as follow:

```
  var liveDb = new LiveMysql({
    host: '127.0.0.1',
    // Port 3407 as specified in leaderboard.mysql.json
    // If using external MySQL server, the default port is 3306
    port: 3307,
    user: 'root',
    password: 'root',
    database: 'leaderboard'
  });
```

The leaderboard.mysql.json file is 

```
{
  "port": 3307,
  "initialize": "leaderboard.sql"
}
```
