### ISSUE TITLE
Not installing on latest Meteor

### ISSUE THREAD

**Issue by uumairr** [numtel/meteor-mysql-server#9]
I am trying to install this package but i am getting following error.
Need help please.

`4 warnings and 13 errors generated.
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error:`make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/Users/umair/.meteor/packages/meteor-tool/.1.4.1_1.10jgzqm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/Users/umair/.meteor/packages/meteor-tool/.1.4.1_1.10jgzqm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/umair/.meteor/packages/meteor-tool/.1.4.1_1.10jgzqm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd /Users/umair/.meteor/packages/numtel_mysql-server/.1.0.1.gnzz6e++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-4udg2u/node_modules/bcrypt
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/umair/.meteor/packages/meteor-tool/.1.4.1_1.10jgzqm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/umair/.meteor/packages/meteor-tool/.1.4.1_1.10jgzqm++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! bcrypt@0.8.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/umair/.meteor/packages/numtel_mysql-server/.1.0.1.gnzz6e++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-4udg2u/npm-debug.log
`

**Comment by omkarpg0931** [comment]
Facing same problem.
tried all the solutions given for error "Failed at the bcrypt@0.8.2 install script 'node-gyp rebuild'.".
Still facing same issue.

**Comment by kumarravigithub** [comment]
Same issue. Anybody there???

**Comment by numtel** [comment]
Nobody is here. You're welcome to submit a pull request. I haven't kept up with hanged to the internals of Meteor since making this package.

**Comment by WOLKkr** [comment]
Pls, fix it!

**Comment by alexpanov** [comment]
@numtel it is hard to convince people to submit pull requests when there is #8 that's open for more than a year and is literally 2 lines of code.

I was about to fork the repo, but I am not probably going to do that now.
